--- 
addons: 
  android: ~
  artifacts: true
  sauce_connect: true
before_install: 
  - "sudo apt-get install libxss1 libappindicator1 libindicator7"
  - "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  - "sudo apt-get install -f"
  - "sudo dpkg -i google-chrome*.deb"
  - "sudo apt-get install openjdk-7-jdk"
  - "wget http://dl.google.com/android/android-sdk_r24.2-linux.tgz"
  - "tar -xvf android-sdk_r24.2-linux.tgz"
  - "cd android-sdk-linux/tools"
  - "( while [ 1 ]; do sleep 5; echo y; done ) | ./android update sdk --no-ui -t 1,2,3,7,32,65,119,143,153,154,168"
  - "echo no | ./android create avd --force -n test -t android-22 --abi x86"
  - "./emulator -avd test -no-skin -no-audio -no-window &"
before_script:
  - "cd ~"
  - "npm install -g chromedriver"
  - "npm install -g protractor"
  - "npm install -g protractor-html-screenshot-reporter"
  - "npm install -g wd"
  - "npm install -g wd-bridge"
  - "npm install jasmine-reporters"
  - "npm install -g appium"
  - "npm install -g chrome"
  - "npm install mkdirp"
  - "npm install underscore"
  - "npm install -g android"
  - "webdriver-manager update"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
  - appium
dist: trusty
env: 
  global: 
    - 
      secure: bartvitaly
    - 
      secure: 96fe819c-b6e1-472f-9e98-5793cacb1d62
language: node_js
node_js: 
  - "4"
script: 
  - "protractor conf/sauce.js"
