--- 
addons: 
  firefox: "39.0"
android: 
before_script:
  - "nvm install node 4"
  - "npm install -g chromedriver"
  - "npm install -g protractor"
  - "npm install -g protractor-html-screenshot-reporter"
  - "npm install -g wd"
  - "npm install -g wd-bridge"
  - "npm install jasmine-reporters"
  - "npm install mkdirp"
  - "npm install math"
  - "npm install properties-reader"
  - "npm install properties"
  - "npm install path"
  - "npm install underscore"
  - "webdriver-manager update"
cache: false
jdk: oraclejdk7
language: android
script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3m"
  - "protractor conf/e2e_create.js"
sudo: false