--- 
android: 
  components:
    - platform-tools		
    - tools
    - build-tools-22.0.1
    - android-22
    - sys-img-armeabi-v7a-android-22
    - add-on
    - extra
  licenses: 
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+
before_script:
  - "nvm install node 5"
  - "echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a"
  - "emulator -avd test -no-audio -no-skin -no-window -gpu off -wipe-data&"
  - android-wait-for-emulator
  - "adb shell input keyevent 82 &"
  - "npm install -g chromedriver"
  - "npm install -g appium"
  - "nohup xvfb-run appium &"
  - "npm install -g protractor"
  - "npm install -g protractor-html-screenshot-reporter"
  - "npm install -g wd"
  - "npm install -g wd-bridge"
  - "npm install jasmine-reporters"
  - "npm install mkdirp"
  - "npm install math"
  - "npm install properties-reader"
  - "npm install properties"
  - "npm install path"
  - "npm install underscore"
  - "npm install -g android"
  - "webdriver-manager update"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
cache: false
jdk: oraclejdk7
language: android
script: 
  - "protractor conf/e2e_mobile.js"
sudo: false
