--- 
addons: 
  firefox: "39.0"
android: 
  components: 
  licenses: 
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+
before_script: 
  - "nvm install 4"
  - "npm install -g protractor"
  - "npm install -g protractor-html-screenshot-reporter"
  - "npm install -g wd"
  - "npm install -g wd-bridge"
  - "npm install jasmine-reporters"
  - "npm install mkdirp"
  - "npm install underscore"
  - "webdriver-manager update"
cache: false
jdk: oraclejdk7
language: android
script: 
  - "protractor conf/e2e_web.js"
sudo: false