--- 
addons: 
  sauce_connect: true
before_script: 
  - "npm install -g grunt-cli"
  - "npm install -g bower"
  - "npm install -g mkdirp"
  - "npm install -g chromedriver"
  - "npm install -g protractor"
  - "npm install -g protractor-html-screenshot-reporter"
  - "npm install -g wd"
  - "npm install -g wd-bridge"
  - "npm install -g jasmine-reporters"
  - "npm install -g mkdirp"
  - "npm install -g appium@1.4.16"
  - "npm install -g chrome"
  - "webdriver-manager update"
env: 
  global: 
    - 
      secure: bartvitaly
    - 
      secure: 96fe819c-b6e1-472f-9e98-5793cacb1d62
language: node_js
node_js: 
  - "4"
script: 
  - "protractor sauce.js"
before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable