--- 
addons: 
  firefox: "39.0"
android: 
  components: 
    - build-tools-22.0.1
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra
  licenses: 
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+
before_script:
  - "cd ~/build"
  - "ls -la"
cache: false
jdk: oraclejdk7
language: android
script: 
  - "adb shell input keyevent 82 &"
  - "protractor conf/e2e_mobile.js"
sudo: false
