--- 
android: 
  components: 
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
before_script: 
  - "echo no | android create avd --force -n test -t \"Google Inc.:Google APIs:\"$ANDROID_API_LEVEL --abi google_apis/armeabi-v7a"
  - "emulator -avd test -no-skin -no-audio -no-window &"
cache: false
env: 
  global: 
    - ANDROID_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=21.1.2
jdk: oraclejdk7
language: android
script: 
  - ./wait_for_emulator
  - "./gradlew connectedCheck -PdisablePreDex"
sudo: false
