--- 
android: 
  components:
    - platform-tools		
    - tools
    - build-tools-23.0.3
    - android-23
    - sys-img-armeabi-v7a-android-23
    - add-on
    - extra
  licenses: 
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+
before_script:
  - "nvm install node 4"
  - "npm install -g chromedriver"
  - "npm install -g appium"
  - "nohup appium &"
  - "echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a"
  - "emulator -avd test -no-audio -no-skin -no-window &"
  - android-wait-for-emulator
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g protractor"
  - "npm install -g protractor-html-screenshot-reporter"
  - "npm install -g wd"
  - "npm install -g wd-bridge"
  - "npm install jasmine-reporters"
  - "npm install mkdirp"
  - "npm install math"
  - "npm install properties-reader"
  - "npm install properties"
  - "npm install path"
  - "npm install underscore"
  - "npm install -g android"
  - "webdriver-manager update"
cache: false
jdk: oraclejdk7
language: android
script:
  - "adb devices -l"
  - "adb shell input keyevent 82 &"
  - "protractor conf/e2e_mobile.js"
sudo: false
